add solution for task "tooltip"
js-tasks-ru/htmlcss-20230530_malafeevartem pull request #10
Opened 2023-06-18 16:30 UTC by ArtemMalafeev

2023-06-18 16:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 20:51 UTC, GSemikozov requested changes

2023-06-19 20:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    width: 129px;
ширину и высоту удалим

2023-06-19 20:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: 50%;
left + top + translate - удалим

2023-06-19 20:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 100%;
видимо calc(100% + 8px)

2023-06-21 10:38 UTC, GSemikozov approved these changes

2023-06-21 10:38 UTC, merged