add solution for task "modal"
js-tasks-ru/htmlcss-20230530_malafeevartem pull request #12
Opened 2023-06-19 09:30 UTC by ArtemMalafeev

2023-06-19 09:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 20:52 UTC, GSemikozov requested changes

2023-06-19 20:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: #C4C4C4;
через rgba лучше

2023-06-21 07:23 UTC, ArtemMalafeev commented on 05-lection3/02-modal/modal.css
> +    background-color: #C4C4C4;
Поправил, но не понял, почему именно тут лучше через rgba.

2023-06-21 07:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-21 07:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-21 07:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-21 08:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-21 09:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-21 10:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: #C4C4C4;
потому что фон будет полупрозрачным и про этом не будет делать вложенный контент тоже полупрозрачным, в отличие от того же opacity )

2023-06-21 10:41 UTC, GSemikozov approved these changes

2023-06-21 10:41 UTC, merged