add solution for task "avatar"
js-tasks-ru/htmlcss-20230530_malafeevartem pull request #13
Opened 2023-06-23 07:26 UTC by ArtemMalafeev

Я правильно понял, что никаких размеров для блока мы не задаем ? 
Размер и положение определяем через комбинирование ?
То есть при дальнейшей вставке данного блока на страницу, создаем класс по типу 

.outerBlock__avatar {
  width: 116px;
  height: 116px;
  
  // Позиционирование.
}

2023-06-23 07:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-24 15:37 UTC, GSemikozov requested changes

2023-06-24 15:37 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +        <div class="avatar">
как раз наоборот: у блока есть четко заданные размеры. Если в макете несколько размеров аватара - значит реализуем через модификаторы.

2023-06-25 19:49 UTC, GSemikozov requested changes

2023-06-25 19:49 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__sm {
.avatar_sm

2023-06-25 19:49 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__lg {
.avatar_lg

2023-06-25 19:49 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
.avatar_md

2023-06-26 22:50 UTC, GSemikozov approved these changes

2023-06-26 22:51 UTC, merged