DZ4 button
js-tasks-ru/htmlcss-20230530_malafeevartem pull request #4
Opened 2023-06-08 10:27 UTC by ArtemMalafeev

2023-06-08 10:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-09 13:46 UTC, GSemikozov requested changes

2023-06-09 13:46 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает паддингов

2023-06-09 13:46 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary {
а где _primary?)

2023-06-09 13:46 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2023-06-12 11:53 UTC, ArtemMalafeev commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
+

2023-06-12 12:41 UTC, ArtemMalafeev commented on 03-lection1/01-button/button.css
> +
Добавил, но не понял на что ориентироваться. Подобрал такое значение, при которых ширина кнопки остается 189px.

2023-06-12 12:47 UTC, ArtemMalafeev commented on 03-lection1/01-button/button.css
> +.button_secondary {
Я понял так.
Модификатор нужно определять, когда изменяем базовый внешний вид элемента/блока.
Вариант primary определил как базовый (button) и от него создавал модификаторы для _secondary и _alternate.
Если primary тоже модификатор, тогда непонятно как выглядит базовая кнопка, точнее color, background-color, :hover.

Переделал под _primary.

2023-06-12 20:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary {
в том-то и дело, что у нас есть четко определенные три типа кнопок, "базовую" кнопку в чистом виде нигде не используем. Поэтому надо все-таки поправить

2023-06-12 20:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
в макете сверху 15, снизу 14, по краям можно ставить 15

2023-06-13 12:49 UTC, ArtemMalafeev commented on 03-lection1/01-button/button.css
> +
👍

2023-06-13 12:49 UTC, ArtemMalafeev commented on 03-lection1/01-button/button.css
> +.button_secondary {
👍

2023-06-15 20:14 UTC, GSemikozov approved these changes

2023-06-15 20:14 UTC, merged