dz9-preview-cards
js-tasks-ru/htmlcss-20230530_malafeevartem pull request #9
Opened 2023-06-16 11:45 UTC by ArtemMalafeev

![image](https://github.com/js-tasks-ru/htmlcss-20230530_malafeevartem/assets/83393982/4bed7fb0-1a50-40ae-aa7f-d45f4cb898f1)

Не понял этот момент в домашней работе с карточками, вставил просто картинкой превью для гистограммы.

2023-06-18 13:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-18 13:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-18 13:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 20:49 UTC, GSemikozov requested changes

2023-06-19 20:49 UTC, GSemikozov commented on components/card/card.css
> +    padding: 80px 24px 30px 26px;
отступ сверху нужно определить по карте где он наименьший (тот и будет общим)

2023-06-19 20:49 UTC, GSemikozov commented on components/card/card.css
> +    row-gap: 75px;
отступ определяем по той карте где он наименьший

2023-06-19 20:49 UTC, GSemikozov commented on components/page/page.css
> +    padding: 67px 165px 204px;
у нас есть контейнер, не нужны такие паддинги слева-справа)

2023-06-19 20:49 UTC, GSemikozov commented on components/preview/preview.css
> +    padding: 0 165px;
нужно использовать контейнер, чтобы не задавать во всех блоках такие паддинги чтобы выравнивать контент

2023-06-19 20:49 UTC, GSemikozov commented on index.html
> +                            <h2 class="card__title">Tooltip</h2>
лучше хотя бы h3

2023-06-19 20:50 UTC, GSemikozov reviewed
в картах в виде превью используется разметка реальных компонентов а не картинки

2023-06-21 08:00 UTC, ArtemMalafeev commented on components/card/card.css
> +    padding: 80px 24px 30px 26px;
Делал по вкладке lesson2 в figme, общий style-guide не открывал. Отсюда и недочеты по отступам.
Так же этого элемента нет внутри карточки в lesson 2.

![Снимок экрана 2023-06-21 в 10 58 31](https://github.com/js-tasks-ru/htmlcss-20230530_malafeevartem/assets/83393982/f2d1b3c1-b991-43e7-b729-f9ab1aa726b9)

2023-06-21 08:15 UTC, ArtemMalafeev commented on components/page/page.css
> +    padding: 67px 165px 204px;
Удалил

2023-06-21 08:19 UTC, ArtemMalafeev commented on components/preview/preview.css
> +    padding: 0 165px;
Убрал с .preview, и повесил на preview__cards.

2023-06-21 10:17 UTC, GSemikozov approved these changes

2023-06-21 10:17 UTC, merged